### ISSUE TITLE
Is it possible without sudo requirement?

### ISSUE THREAD

**Issue by gavsiu** [Kwaadpepper/msi-keyboard-CLI#11]
Both msi-keyboard-CLI.js and msibacklight requires me to input a password. This means I cannot have it start as a service on boot.

Although with a lot less options, [this](https://github.com/bparker06/msi-keyboard) backlight enabler does not require sudo permissions.

Is there a way to launch this without asking for my password?

**Comment by Kwaadpepper** [comment]
sorry but no, the lib it depends on require that root launches the thing, But if you want you can use the root crontab to launch your service `sudo crontab -e`

**Comment by gavsiu** [comment]
Thanks, but I'll just use the other one unless this changes in the future. I want to be able to write custom scripts to change the colors, not only start on boot. I liked that this had fade.
