### ISSUE TITLE
Colors not changing after npm install

### ISSUE THREAD

**Issue by raedeus** [Kwaadpepper/msi-keyboard-CLI#14]
Hello,

First of all. Thanks so much for this project!

After installing via the npm method describe firstly in the README, and re-opening the terminal, I attempt to run "sudo msikeyboard -c green". Unfortunately, nothing happens.

I'm running an MSI Ghost, G6QE with SteelSeries keyboard.

I had originally tried out the GUI option on the same computer, same OS but have since reformatted and am trying out the CLI. 

OS is Ubuntu MATE 16.04.

Thanks for your time and consideration.

- raedeus

**Comment by Kwaadpepper** [comment]
Is there any errors output ? You could try https://github.com/stevelacy/msi-keyboard to ask if your laptop is supported by the library.

**Comment by raedeus** [comment]
Hello! Thanks for your response.

There are no errors. The CLI just moves to a new line as though the command was executed.

Funny thing is the GUI worked after a bunch of troubleshooting with node getting it to build. The npm install went without a hitch.
- raedeus

**Comment by Kwaadpepper** [comment]
Have you any of these installed ?
Generic Linux: libusb-dev libusb-1.0-0-dev
