### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by RD1945** [Kwaadpepper/msi-keyboard-CLI#2]
Hello,

After I installed the necessary modules by typing 'npm install' and run the program "nodejs msi-keyboard-CLI.js -k on" I get the following error: **Cannot find module '/home/michel/Downloads/.msi-klm/node_modules/node-hid/build/HID/v0.5.1/Release/node-v11-linux-x64/HID.node'**.

If I check the folders there is no **node-v11-linux-x64**. Only a **node-v47-linux-x64**

Please help

**Comment by Kwaadpepper** [comment]
This is no bug with msi-keyboard-CLI
Repost your bug in https://github.com/wearefractal/msi-keyboard, node-hid is a dependency of this program.

Also before this you should try checking your node version the v5 seems to not work in some cases
cf https://github.com/mapbox/node-sqlite3/issues/537

It is working fine here npm 1.4.21 nodejs v0.10.25.
Try reclonning the project and running
`npm install`
`./msibacklight -k on`

**Comment by RD1945** [comment]
Thank you for this answer. I posted in the other forum. I have both the v5 node and the 0.10.25 nodejs. Tried with both. No luck yet.

**Comment by Kwaadpepper** [comment]
But its with the v5 node that maybe the problem, you'll have to try an earlier version, that was my point actually.

**Comment by RD1945** [comment]
Actually tried the 4.2.2 version today. No luck. Same result.

**Comment by RD1945** [comment]
I think it is due to my Ubuntu version. First I tried it with 16.04, didn't work. Now with Ubuntu 15.10 it works just fine. Don't know why but it works. Thanks for the awesome program.

**Comment by KirillGrigoriev** [comment]
Seems like node.js is installed incorrect. Try to delete node.js and all node.js files, and install it again from sourses. It will something like this on CentOS 7:

1) wget https://nodejs.org/dist/v5.1.0/node-v5.1.0.tar.gz
2) tar xzvf node-v\* && cd node-v*
3) yum install -y make gcc*
4) ./configure
5) make
6) make install

It work for me.
