### ISSUE TITLE
Error: cannot open device with vendor id 0x1770 and product id 0xff00

### ISSUE THREAD

**Issue by natedawwgg** [Kwaadpepper/msi-keyboard-CLI#24]
Hi there,

I'm not very experienced with linux and it's use of terminal at the moment but I am slowly learning. I am trying to get my old gt70 keyboard to light up different colors and I am currently having an issue in doing so.

in ~/.msi-klm$ I am typing nodejs msi-keyboard-CLI.js -c green (I assume to change all keys to green) and  I receive this message back.

/home/nathan/.msi-klm/node_modules/node-hid/nodehid.js:24
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

Error: cannot open device with vendor id 0x1770 and product id 0xff00
    at Error (native)
    at new HID (/home/nathan/.msi-klm/node_modules/node-hid/nodehid.js:24:17)
    at module.exports (/home/nathan/.msi-klm/node_modules/msi-keyboard/lib/findKeyboard.js:8:14)
    at Object.<anonymous> (/home/nathan/.msi-klm/msi-keyboard-CLI.js:37:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

I am not entirely sure what is going on as I have followed the install instructions correctly. When I use -sudo nodejs msi-keyboard-CLI.js -k on - it turns on the keyboard so I feel as if I have got that right, it just reverts to default white.

Any help would be greatly appreciated, thank you.

**Comment by siemovit** [comment]
Hello @natedawwgg  I got the same issue, please tell me if you found a solution.

**Comment by natedawwgg** [comment]
Unfortunately no resolution for myself as of yet @siemovit

**Comment by eduardoleal** [comment]
I`m having the same problem guys. Any solution on that?

**Comment by Kwaadpepper** [comment]
Please if you use nodejs try using "sudo".



Le lun. 2 juil. 2018 à 22:51, Eduardo Leal <notifications@github.com> a
écrit :

**Comment by Kwaadpepper** [comment]
I just updated the examples on readme :

use 'msibacklight -c green ' or 'sudo nodejs msi-keyboard-CLI.js -c green'

**Comment by ShcherbinaVitali** [comment]
this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^
Error: cannot open device with vendor id 0x1770 and product id 0xff00

msi gs65 8RE - both command don't work.

**Comment by Kwaadpepper** [comment]
Which version of nodejs are you using ?
Have you installed ```libusb-1.0-0-dev``` ?

**Comment by ShcherbinaVitali** [comment]
GS65-Stealth-Thin-8RE:~$ node -v
v8.10.0
yes, I installed libusb-1.0-0-dev

**Comment by Kwaadpepper** [comment]
You could try using this to see if it works.
https://github.com/stevelacy/msi-keyboard-gui

This error is coming from node-hid. So it may be that your keyboard is not supported.

My project is just an interface for @stevelacy s project https://github.com/stevelacy/msi-keyboard . Let me know how it goes for you.

Also it may no work with NVM. You could try to run the script with su account ?

**Comment by ShcherbinaVitali** [comment]
I found https://github.com/Askannz/msi-perkeyrgb#branch=master python CLI tool and it works for me

**Comment by vipermu** [comment]
> I found https://github.com/Askannz/msi-perkeyrgb#branch=master python CLI tool and it works for me

It worked for me (MSI GS65), thanks!

**Comment by Kwaadpepper** [comment]
Thank you for your comment i'll put the link on the readme page :)
