### ISSUE TITLE
Error after latest msi-keyboard (0.3.0)

### ISSUE THREAD

**Issue by dimitriscsd** [Kwaadpepper/msi-keyboard-CLI#8]
Hello.

I am getting this when I'm trying to use the CLI. Any idea what the reason would be?

$ sudo msikeyboard -c green
/usr/local/lib/node_modules/msi-keyboard-cli/msi-keyboard-CLI.js:348
        keyboard.color (section, keyboardArgs[section]);
                 ^

TypeError: keyboard.color is not a function
    at
/usr/local/lib/node_modules/msi-keyboard-cli/msi-keyboard-CLI.js:348:18
    at FSReqWrap.cb [as oncomplete](fs.js:216:19)

**Comment by kasiarachwal** [comment]
Same issue on Ubuntu 16.04 now.

**Comment by Kwaadpepper** [comment]
hey, i just updated the thing, i had this issue after updating npm, let me know if this is fixed

**Comment by dimitriscsd** [comment]
I only had a few minutes to test this as I'm at work, but it looks like it
works fine now! Thank you!

I will report back if I notice something not working as it should.

**Comment by kasiarachwal** [comment]
Works for me, too. Thanks!
