### ISSUE TITLE
support centos 7

### ISSUE THREAD

**Issue by paridin** [Kwaadpepper/msi-keyboard-CLI#9]
When I try to install with `sudo npm install msi-keyboard-cli -g`  I got

```
make: Entering directory `/usr/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
```

It is because it didn't found `libusb.h` but i have `libusb-devel` installed

```
Package 1:libusb-devel-0.1.4-3.el7.x86_64 already installed and latest version
```

So after looking for provider of `libusb.h` I found `libusbx-devel` is the provider on centos

 `sudo yum install libusbx-devel` and  `sudo npm install msi-keyboard-cli -g`  it will install witout problems

But now the issue is with a function `sudo msikeyboard -k on`
#8

```
/usr/lib/node_modules/msi-keyboard-cli/msi-keyboard-CLI.js:348
        keyboard.color (section, keyboardArgs[section]);
                 ^

TypeError: keyboard.color is not a function
    at /usr/lib/node_modules/msi-keyboard-cli/msi-keyboard-CLI.js:348:18
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
```

```
node --version v4.4.4
npm@3.9.0 /usr/lib/node_modules/npm
```

same error on `node 5.11.1`

**Comment by Kwaadpepper** [comment]
Your issue is similar to #8 let me know if this is fixed or not. It seemed to happen as i updated npm. This may be fixed now.

Also thanks for pointing out the real package on CENTOS, I’ll update the README accordingly.
